# Generated by Django 4.2.3 on 2023-08-22 15:53

from django.db import migrations, models
import django.db.models.deletion
import pagos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateTimeField(auto_created=True, blank=True)),
                ('estado', models.CharField(auto_created='Pendiente', blank=True, choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], max_length=30)),
                ('numero_comprobante', models.CharField(max_length=50)),
                ('monto', models.IntegerField()),
                ('comprobante', models.ImageField(upload_to=pagos.models.save_path)),
                ('motivo_rechazo', models.TextField(blank=True, max_length=1000, null=True)),
                ('fecha_aprobado', models.DateTimeField(blank=True)),
                ('acreditado', models.BooleanField(default=False)),
                ('preventa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.preventa')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
            },
        ),
    ]
