# Generated by Django 4.2.3 on 2023-08-19 22:03

from django.db import migrations, models
import django.db.models.deletion
import pagos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tareas', '0005_preventa_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_comprobante', models.IntegerField()),
                ('monto', models.IntegerField()),
                ('comprobante', models.ImageField(upload_to=pagos.models.save_path)),
                ('motivo_rechazo', models.TextField(max_length=1000)),
                ('aprobado', models.BooleanField(default=False)),
                ('acreditado', models.BooleanField(default=False)),
                ('preventa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.preventa')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
            },
        ),
    ]
