# Generated by Django 4.2.3 on 2023-11-09 18:42

from django.db import migrations, models
import django.db.models.deletion
import pagos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_deposito', models.DateField()),
                ('tipo_deposito', models.CharField(choices=[('SICE Debito', 'SICE Debito'), ('SICE Cheque', 'SICE Cheque'), ('SICE Efectivo', 'SICE Efectivo'), ('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Cheque', 'Cheque')], max_length=30)),
                ('banco_destino', models.CharField(choices=[('Frances', 'Frances'), ('Provincia', 'Provincia'), ('Santander', 'Santander')], max_length=30)),
                ('cuenta', models.CharField(choices=[('Recaudadora Frances', 'Recaudadora Frances'), ('VW Credit 3046', 'VW Credit 3046'), ('Espasa', 'Espasa')], max_length=30)),
                ('numero_comprobante', models.CharField(max_length=50, unique=True)),
                ('depositante_cuit', models.IntegerField(blank=True, null=True, verbose_name='Datos Depositante')),
                ('monto', models.IntegerField()),
                ('comprobante', models.ImageField(upload_to=pagos.models.save_path)),
                ('motivo_rechazo', models.TextField(blank=True, max_length=1000, null=True)),
                ('administracion', models.CharField(blank=True, choices=[('1Pendiente', 'Pendiente'), ('2Aprobado', 'Aprobado'), ('3Rechazado', 'Rechazado')], default='1Pendiente', max_length=30)),
                ('carga_crm', models.BooleanField(default=False)),
                ('estado', models.CharField(blank=True, choices=[('1Pendiente', 'Pendiente'), ('2Aprobado', 'Aprobado'), ('3Rechazado', 'Rechazado')], default='1Pendiente', max_length=30)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_aprobado', models.DateTimeField(blank=True, null=True)),
                ('acreditado', models.BooleanField(default=False)),
                ('preventa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.preventa')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
            },
        ),
    ]
