# Generated by Django 4.2.3 on 2023-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_carga',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
