# Generated by Django 4.2.3 on 2023-08-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='motivo_rechazo',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
