# Generated by Django 4.2.3 on 2023-08-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_pago_fecha_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_aprobado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
