# Generated by Django 4.2.3 on 2023-08-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_pago_motivo_rechazo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='aprobado',
        ),
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], max_length=30, null=True),
        ),
    ]
