# Generated by Django 4.2.3 on 2023-08-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_pago_fecha_aprobado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(blank=True, choices=[(1, 'Pendiente'), (2, 'Aprobado'), (3, 'Rechazado')], default='Pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
