# Generated by Django 4.2.3 on 2023-08-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_pago_depositante_cuit_alter_pago_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='depositante_cuit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Datos Depositante'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='numero_comprobante',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
