# Generated by Django 4.2.3 on 2023-08-29 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_alter_pago_depositante_cuit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='banco_destino',
            field=models.CharField(choices=[('Frances', 'Frances'), ('Provincia', 'Provincia'), ('Santander', 'Santander')], default='Frances', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='cuenta',
            field=models.CharField(choices=[('Recaudadora Frances', 'Recaudadora Frances'), ('VW Credit 3046', 'VW Credit 3046'), ('Espasa', 'Espasa')], default='Recaudadora Frances', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_deposito',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_deposito',
            field=models.CharField(choices=[('SICE Debito', 'SICE Debito'), ('SICE Cheque', 'SICE Cheque'), ('SICE Efectivo', 'SICE Efectivo'), ('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Cheque', 'Cheque')], default='SICE Debito', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
