# Generated by Django 4.2.3 on 2023-08-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0009_pago_administracion_pago_carga_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='carga_crm',
            field=models.BooleanField(default=False),
        ),
    ]
