# Generated by Django 4.2.3 on 2023-10-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('tipo', models.CharField(max_length=300)),
                ('preventa', models.CharField(max_length=50)),
                ('log', models.TextField()),
            ],
        ),
    ]
