# Generated by Django 4.2.3 on 2023-07-17 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preventa', models.CharField(help_text='Ejemplo 12345/1', max_length=8, unique=True)),
                ('tipo_venta', models.CharField(choices=[('C', 'Contado'), ('F', 'Financiado')], max_length=15)),
                ('tipo_cliente', models.CharField(choices=[('PF', 'Persona Fisica'), ('PJ', 'Persona Juridica')], max_length=30)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='')),
                ('completo', models.BooleanField(default=False)),
                ('creado', models.DateField(auto_now_add=True)),
                ('pv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.preventa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['completo'],
            },
        ),
    ]
