# Generated by Django 4.2.3 on 2023-08-22 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tareas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preventa', models.CharField(help_text='Ejemplo 12345/1', max_length=8, unique=True)),
                ('tipo_venta', models.CharField(choices=[('Contado', 'Contado'), ('Financiado', 'Financiado')], max_length=15)),
                ('tipo_cliente', models.CharField(blank=True, choices=[('Persona Fisica', 'Persona Fisica'), ('Persona Juridica', 'Persona Juridica')], max_length=30, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a')], max_length=30, null=True)),
                ('co_titular', models.CharField(blank=True, choices=[('No', 'No'), ('Si', 'Si')], max_length=2, null=True)),
                ('cedulas_azules', models.IntegerField(blank=True, null=True)),
                ('socios', models.IntegerField(blank=True, null=True)),
                ('retira_unidad', models.CharField(blank=True, choices=[('Transportista', 'Transportista'), ('Individuo', 'Individuo'), ('Titular', 'Titular')], max_length=15, null=True)),
                ('contado', models.BooleanField(null=True)),
                ('completo', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vendedor',
                'verbose_name_plural': 'vendedores',
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('descarga', models.CharField(blank=True, max_length=30, null=True)),
                ('adjunto', models.FileField(blank=True, null=True, upload_to=tareas.models.save_path)),
                ('completo', models.BooleanField(default=False)),
                ('actualizado', models.DateField(auto_now=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('pv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.preventa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
                'ordering': ['completo'],
            },
        ),
        migrations.AddField(
            model_name='preventa',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.vendedor'),
        ),
    ]
