# Generated by Django 4.2.3 on 2023-08-28 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionTareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descipcion', models.TextField()),
                ('descarga', models.FileField(upload_to='archivos_para_descargar')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.tipotarea')),
            ],
        ),
    ]
