# Generated by Django 4.2.3 on 2023-07-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventa',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Casado/a', 'Casado/a'), ('Soltero/a', 'Soltero/a')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='preventa',
            name='tipo_cliente',
            field=models.CharField(blank=True, choices=[('Persona Fisica', 'Persona Fisica'), ('Persona Juridica', 'Persona Juridica')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='descarga',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
