# Generated by Django 4.2.3 on 2023-07-18 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='descarga',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Adjuntar archivo'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='completo',
            field=models.BooleanField(default=False, verbose_name='Tarea Realizada'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='creado',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion de la tarea'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='pv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.preventa', verbose_name='Preventa'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Tarea'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
