# Generated by Django 4.2.3 on 2023-07-20 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tareas.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name': 'vendedor', 'verbose_name_plural': 'vendedores'},
        ),
        migrations.AlterField(
            model_name='tareas',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to=tareas.models.save_path),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='creado',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='pv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.preventa'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
