# Generated by Django 4.2.3 on 2023-07-18 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_tareas_descarga_alter_tareas_adjunto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareasPreventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retira_unidad', models.IntegerField(blank=True, choices=[(1, 'Transportista'), (2, 'Individuo'), (3, 'Titular')], max_length=15, null=True)),
                ('cedulas_azules', models.IntegerField(blank=True, null=True)),
                ('socios', models.IntegerField(blank=True, null=True)),
                ('preventa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.preventa', verbose_name='Preventa')),
            ],
        ),
    ]
