# Generated by Django 4.2.3 on 2023-07-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_preventa_estado_civil_alter_preventa_tipo_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventa',
            name='co_titular',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Si', 'Si')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='preventa',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a')], max_length=30, null=True),
        ),
    ]
