# Generated by Django 4.2.3 on 2023-07-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_alter_vendedor_options_alter_tareas_adjunto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareas',
            options={'ordering': ['completo'], 'verbose_name': 'tarea', 'verbose_name_plural': 'tareas'},
        ),
        migrations.AlterField(
            model_name='tareas',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
