# Generated by Django 4.2.3 on 2023-08-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_remove_asignaciontareas_descipcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='descarga',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
