# Generated by Django 4.2.3 on 2023-07-20 16:42

from django.db import migrations, models
import tareas.models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_alter_tareas_options_alter_tareas_adjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to=tareas.models.save_path),
        ),
    ]
