# Generated by Django 4.2.3 on 2023-07-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_tareaspreventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventa',
            name='cedulas_azules',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventa',
            name='retira_unidad',
            field=models.IntegerField(blank=True, choices=[(1, 'Transportista'), (2, 'Individuo'), (3, 'Titular')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='preventa',
            name='socios',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
