# Generated by Django 4.2.3 on 2023-08-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_preventa_co_titular_alter_preventa_estado_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventa',
            name='monto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
