# Generated by Django 4.2.3 on 2023-08-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_preventa_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventa',
            name='saldo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
