# Generated by Django 4.2.3 on 2023-08-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_alter_tareas_descarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='descarga',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
