# Generated by Django 4.2.3 on 2023-07-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_preventa_cedulas_azules_preventa_retira_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventa',
            name='completo',
            field=models.BooleanField(default=False),
        ),
    ]
