# Generated by Django 4.2.3 on 2023-08-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_preventa_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preventa',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='preventa',
            name='saldo',
        ),
        migrations.AddField(
            model_name='preventa',
            name='contado',
            field=models.BooleanField(null=True),
        ),
    ]
