# Generated by Django 4.2.3 on 2023-07-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_alter_preventa_retira_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventa',
            name='retira_unidad',
            field=models.CharField(blank=True, choices=[('Transportista', 'Transportista'), ('Individuo', 'Individuo'), ('Titular', 'Titular')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='preventa',
            name='tipo_cliente',
            field=models.CharField(choices=[('Persona Fisica', 'Persona Fisica'), ('Persona Juridica', 'Persona Juridica')], max_length=30),
        ),
        migrations.AlterField(
            model_name='preventa',
            name='tipo_venta',
            field=models.CharField(choices=[('Contado', 'Contado'), ('Financiado', 'Financiado')], max_length=15),
        ),
    ]
