# Generated by Django 4.2.3 on 2023-09-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0009_remove_tareas_tipo_doc_asignaciontareas_tipo_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='tipo_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.tipodoc'),
        ),
    ]
