# Generated by Django 4.2.3 on 2023-09-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0010_tareas_tipo_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventa',
            name='fecha_preventa',
            field=models.DateField(blank=True, null=True),
        ),
    ]
