# Generated by Django 4.2.3 on 2023-09-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0011_alter_preventa_fecha_preventa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignaciontareas',
            options={'verbose_name': 'asignaciontareas', 'verbose_name_plural': 'asignaciontareas'},
        ),
        migrations.AlterModelOptions(
            name='tipodoc',
            options={'ordering': ['descripcion']},
        ),
        migrations.AddField(
            model_name='tareas',
            name='tipo_tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.tipotarea'),
        ),
    ]
