# Generated by Django 4.2.3 on 2023-09-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0012_alter_asignaciontareas_options_alter_tipodoc_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventa',
            name='preventa',
            field=models.CharField(help_text='Ejemplo 12345/1', max_length=15, unique=True),
        ),
    ]
