# Generated by Django 4.2.3 on 2023-09-29 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tareas', '0013_alter_preventa_preventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventa',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='pv',
        ),
        migrations.AddField(
            model_name='tareas',
            name='pv',
            field=models.ManyToManyField(blank=True, null=True, to='tareas.preventa'),
        ),
    ]
