# Generated by Django 4.2.3 on 2023-09-29 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0014_alter_preventa_user_remove_tareas_pv_tareas_pv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='pv',
        ),
        migrations.AddField(
            model_name='tareas',
            name='pv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.preventa'),
        ),
    ]
