# Generated by Django 4.2.3 on 2023-10-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0015_remove_tareas_pv_tareas_pv'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='crm_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
