# Generated by Django 4.2.3 on 2023-10-27 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tareas', '0017_preventa_tareas_de_usuario_crm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(choices=[('Triunvirato', 'Triunvirato'), ('Cordoba', 'Cordoba'), ('Thomas', 'Thomas'), ('Lima', 'Lima'), ('Colon', 'Colon')], max_length=30)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vendedor',
            name='suervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.supervisor'),
        ),
    ]
