# Generated by Django 4.2.3 on 2023-10-27 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tareas', '0018_supervisor_vendedor_suervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(choices=[('Triunvirato', 'Triunvirato'), ('Cordoba', 'Cordoba'), ('Thomas', 'Thomas'), ('Lima', 'Lima'), ('Colon', 'Colon')], max_length=30)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='suervisor',
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.sucursal'),
        ),
    ]
