# Generated by Django 4.2.3 on 2023-11-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0019_sucursal_remove_vendedor_suervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventa',
            name='tareas_de_usuario_crm',
            field=models.BooleanField(default=False, verbose_name='Doc-User'),
        ),
    ]
