# Generated by Django 4.2.3 on 2023-11-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertpdf',
            name='archivo2',
            field=models.ImageField(blank=True, null=True, upload_to='temp'),
        ),
        migrations.AlterField(
            model_name='convertpdf',
            name='archivo3',
            field=models.ImageField(blank=True, null=True, upload_to='temp'),
        ),
        migrations.AlterField(
            model_name='convertpdf',
            name='archivo4',
            field=models.ImageField(blank=True, null=True, upload_to='temp'),
        ),
        migrations.AlterField(
            model_name='convertpdf',
            name='archivo5',
            field=models.ImageField(blank=True, null=True, upload_to='temp'),
        ),
        migrations.AlterField(
            model_name='convertpdf',
            name='archivo6',
            field=models.ImageField(blank=True, null=True, upload_to='temp'),
        ),
        migrations.AlterField(
            model_name='convertpdf',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
