version: '3'

services:
  espasa-app:
    container_name: espasa-app
    image: espasa-app:v0.5
    volumes:
      - ../db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
      - ./static:/app/static
    ports:
      - "8000:8000"
    extra_hosts:
      - "mail.backoffice.com.ar:10.0.4.50"
    networks:
      - espasa-network

  nginx-espasa:
    container_name: nginx-espasa
    image: nginx-espasa:v0.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - espasa-app
    networks:
      - espasa-network

networks:
  espasa-network:
    driver: bridge
