version: '3'

services:
  espasa-app:
    image: espasa-app:001
    ports:
      - "8000:8000"

  nginx-espasa:
    image: nginx-espasa:004
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - espasa-app
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; certbot renew; done & nginx -g \"daemon off;\"'"
